#!name=去APP开屏广告
#!desc=去APP开屏广告
#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/startingad.png
#!homepage=https://github.com/deezertidal
#!author=ddgksf2013
# # from https://github.com/deezertidal/shadowrocket-rules
[MITM]
hostname = %APPEND% *.bdstatic.com,m5.amap.com,appapi.huazhu.com,testflight.apple.com,*.music.163.com,pages.xiaohongshu.com, www.xiaohongshu.com, static.zhihu.com

[URL Rewrite]

# ======= B ======= #
# > 百度地图开屏广告
^https:\/\/dss0\.bdstatic\.com\/.+/tam-ogel\/.+\.(jpg|mp4) - reject


# ======= G ======= #
# > 高德
^https?:\/\/m5.amap.com\/ws\/valueadded\/ - reject


# ======= H ======= #
# > 华住
^https?:\/\/appapi\.huazhu\.com:\d{4}\/client\/app\/getAppStartPage\/ - reject


# ======= T ======= #
# > 解除国区TF下载限制
^https?:\/\/testflight\.apple\.com\/v2\/accounts\/.*\/apps\/\d*/builds/\d*/install request-body storefrontId" : ".*" request-body storefrontId" : "143441-1,29"

# ======= W ======= #
# > 网易云音乐
^https?:\/\/interface(\d)?.music.163.com\/eapi\/ad\/ - reject



# ======= X ======= #

# > 小红书开屏广告@chouchoui
^https:\/\/www\.xiaohongshu\.com\/api\/sns\/v1\/ads\/apple\/record* - reject
^https:\/\/www\.xiaohongshu\.com\/api\/sns\/v1\/tag\/ads_engage* - reject
^https:\/\/www\.xiaohongshu\.com\/api\/sns\/v1\/ads\/resource* - reject
^https:\/\/pages\.xiaohongshu\.com\/data\/native\/matrix_switches* - reject


# ======= Y ======= #

# > Youtube@DivineEngine
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) - 302 $1$2$3
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad - reject
^https?:\/\/youtubei\.googleapis\.com\/youtubei\/v\d\/player\/ad_break - reject
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads - reject
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) - reject
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext - reject


# ======= Z ======= #

# > 知乎网页版强制登陆弹窗@HotKids
^https?:\/\/static\.zhihu\.com\/[^\/]+\/(main|column)\.signflow\.[^.]+.js - reject
